const level1 = new Level(
    [
        /*new OrcGreen(),
        new OrcGreen(),
        new OrcGreen(),
        new OrcGreen(),
        new OrcGreen(),
        new OrcGreen(),
        new OrcGreen(),
        new OrcGreen(),
        new OrcGreen(),
        new OrcRed(),
        new OrcRed(),
        new OrcRed(),
        new OrcRed(),
        new OrcRed(),
        new OrcRed(),
        new OrcRed(),
        new OrcRed(),
        new OrcRed()*/
    ],
    [
        new Firefly(-680),
        new Firefly(20),
        new Firefly(720),
        new Firefly(1420),
        new Firefly(2120),
        new Firefly(2820),
        new Firefly(3520),
        new Firefly(4220),
        new Firefly(4920),
        new Firefly(5620),
        new Firefly(6220),
        new Firefly(6920),
        new Firefly(7620),
        new Firefly(7320),
        new Firefly(7920),
        new Firefly(8620)
    ],
    [
        new BackgroundObject('img/5_background/layers/sky.png', -720),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -720),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', -720),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -720),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', -720),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -720),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', -720),
        new BackgroundObject('img/5_background/layers/sky.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/sky.png', 720),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720),
        new BackgroundObject('img/5_background/layers/sky.png', 720*2),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720*2),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720*2),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720*2),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720*2),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720*2),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 720*2),
        new BackgroundObject('img/5_background/layers/sky.png', 720*3),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720*3),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720*3),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720*3),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720*3),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720*3),
        new BackgroundObject('img/5_background/layers/sky.png', 720*4),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720*4),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720*4),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720*4),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720*4),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720*4),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 720*4),
        new BackgroundObject('img/5_background/layers/sky.png', 720*5),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720*5),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720*5),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720*5),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720*5),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720*5),
    ],
    [
        new Coin(-600, 50),
        new Coin(-550, 0),
        new Coin(-500, 50),
        new Coin(450, 50),
        new Coin(550, 50),
        new Coin(1100, 50),
        new Coin(1200, 50),
        new Coin(1750, 50),
        new Coin(1850, 50),
        new Coin(2400, 50),
        new Coin(2500, 50),
        new Coin(2950, 50),
        new Coin(3000, 0),
        new Coin(3050, 50)
    ],
    [
        new KunaiCoin(-500,120),
        new KunaiCoin(-550,170),
        new KunaiCoin(-600,120),
        new KunaiCoin(500,0),
        new KunaiCoin(1800,0),
        new KunaiCoin(3000,0)
    ]
);