const level1 = new Level(
    [
        new Orc(),
        new Orc(),
        new Orc(),
        new Endboss()
    ],
    [
        new Firefly()
    ],
    [
        new BackgroundObject('img/5_background/layers/sky.png', -720),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -720),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', -720),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -720),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', -720),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -720),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', -720),
        new BackgroundObject('img/5_background/layers/sky.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/sky.png', 720),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720),
        new BackgroundObject('img/5_background/layers/sky.png', 720*2),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720*2),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720*2),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720*2),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720*2),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720*2),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 720*2),
        new BackgroundObject('img/5_background/layers/sky.png', 720*3),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720*3),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720*3),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720*3),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720*3),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720*3),
        new BackgroundObject('img/5_background/layers/sky.png', 720*4),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720*4),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720*4),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720*4),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720*4),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720*4),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 720*4),
        new BackgroundObject('img/5_background/layers/sky.png', 720*5),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720*5),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720*5),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720*5),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720*5),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720*5),
    ]
);